# configuration file for the issue-labeler action.  See workflows/repo.issue.labels.yml


## Issue types
'is.bug':
  - '/^\s*-?\s*\+bug(fix)?$/gm'
'is.enhancement':
  - '/^\s*-?\s*\+enhance(ment)?$/gm'
'is.feature':
  - '/^\s*-?\s*\+feat(ure)?$/gm'
'is.idea':
  - '/^\s*-?\s*\+idea$/gm'
'is.question':
  - '/^\s*-?\s*\+question$/gm'
'is.refactor':
  - '/^\s*-?\s*\+refac(tor)?$/gm'
'is.mantenance':
  - '/^\s*-?\s*\+maint(enance)?$/gm'

## story types
'story.epic':
  - '/^\s*-?\s*\+epic$/gm'
'story.user':
  - '/^\s*s?\s*\+user$/gm'
  - '/^\s*s?\s*\+story$/gm'

## Project areas

'area.actions':
  -'/^\s*-?\s*\[actions\]$/gm'
'area.build':
  -'/^\s*-?\s*\[build\]$/gm'
'area.build-script':
  -'/^\s*-?\s*\[build-script\]$/gm'
'area.code-quality':
  -'/^\s*-?\s*\[code-quality\]$/gm'
'area.community':
  -'/^\s*-?\s*\[community\]$/gm'
'area.docs':
  -'/^\s*-?\s*\[docs\]$/gm'
'area.help':
  -'/^\s*-?\s*\[help\]$/gm'
'area.initialize':
  -'/^\s*-?\s*\[initialize\]$/gm'
'area.invoke-build':
  -'/^\s*-?\s*\[invoke-build\]$/gm'
'area.module':
  -'/^\s*-?\s*\[module\]$/gm'
'area.phase':
  -'/^\s*-?\s*\[phase\]$/gm'
'area.repo':
  -'/^\s*-?\s*\[repo\]$/gm'
'area.runbook':
  -'/^\s*-?\s*\[runbook\]$/gm'
'area.source-info':
  -'/^\s*-?\s*\[source-info\]$/gm'
'area.tasks':
  -'/^\s*-?\s*\[tasks\]$/gm'
'area.template':
  -'/^\s*-?\s*\[template\]$/gm'
'area.tests':
  -'/^\s*-?\s*\[tests\]$/gm'
'area.versioning':
  -'/^\s*-?\s*\[versioning\]$/gm'

## Story point value

'sp.00':
  - '/^\s*-?\s*sp(0)?0$/gm'
'sp.01':
  - '/^\s*-?\s*sp(0)?1$/gm'
'sp.02':
  - '/^\s*-?\s*sp(0)?2$/gm'
'sp.03':
  - '/^\s*-?\s*sp(0)?3$/gm'
'sp.05':
  - '/^\s*-?\s*sp(0)?5$/gm'
'sp.08':
  - '/^\s*-?\s*sp(0)?8$/gm'
'sp.13':
  - '/^\s*-?\s*sp13$/gm'

## Closing reasons

'closed.done':
  - '/^\s*-?\s*(closed|(closed)?\.done)$/gm'
'closed.duplicate':
  - '/^\s*-?\s*(closed)?\.dup(licate)?$/gm'
'closed.invalid':
  - '/^\s*-?\s*(closed)?\.invalid$/gm'
'closed.norepro':
  - '/^\s*-?\s*(closed)?\.norepro$/gm'
'closed.wontfix':
  - '/^\s*-?\s*(closed)?\.wontfix$/gm'


## All new issues should get the "review" flag

'flag.review':
  - '/.*/'
