name: '[mgmt] Issue Labeler'

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

permissions:
  issues: write
  pull-requests: write
  contents: read
  
jobs:
  triage:
    name: Triage issues and prs
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        include-title: 1
        include-body: 1
