name: Update StoryPoint field when labeled with sp value

on:
  label:
    types:
      - created
      - edited
      - deleted

env:
  project_number: 3
  project_token: ${{ secrets.ACTION_ADDTOPROJECT }}
  project_sp_01: '[{\"name\": \"StoryPoints\", \"type\": \"Number\", \"value\": "1"}]'
  project_sp_02: '[{\"name\": \"StoryPoints\", \"type\": \"Number\", \"value\": "2"}]'
  project_sp_03: '[{\"name\": \"StoryPoints\", \"type\": \"Number\", \"value\": "3"}]'
  project_sp_05: '[{\"name\": \"StoryPoints\", \"type\": \"Number\", \"value\": "5"}]'
  project_sp_08: '[{\"name\": \"StoryPoints\", \"type\": \"Number\", \"value\": "8"}]'
  project_sp_13: '[{\"name\": \"StoryPoints\", \"type\": \"Number\", \"value\": "13"}]'

jobs:
  issue_labeled:
    name: Issue labeled
    runs-on: ubuntu-latest
    steps:
      - name: Set StoryPoints to 1
        if: github.event_name == 'issues' && github.event.label.name == 'sp.01'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: ${{ env.project_sp_01 }}
      - name: Set StoryPoints to 2
        if: github.event_name == 'issues' && github.event.label.name == 'sp.02'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: ${{ env.project_sp_02 }}
      - name: Set StoryPoints to 3
        if: github.event_name == 'issues' && github.event.label.name == 'sp.03'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: ${{ env.project_sp_03 }}
      - name: Set StoryPoints to 5
        if: github.event_name == 'issues' && github.event.label.name == 'sp.05'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: ${{ env.project_sp_05 }}
      - name: Set StoryPoints to 8
        if: github.event_name == 'issues' && github.event.label.name == 'sp.08'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: ${{ env.project_sp_08 }}
      - name: Set StoryPoints to 13
        if: github.event_name == 'issues' && github.event.label.name == 'sp.13'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: ${{ env.project_sp_13 }}
  pr_labeled:
    name: Pull request labeled
    runs-on: ubuntu-latest
    steps:
      - name: Set StoryPoints to 1
        if: github.event_name == 'pull_requests' && github.event.label.name == 'sp.01'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          custom_field_values: ${{ env.project_sp_01 }}
      - name: Set StoryPoints to 2
        if: github.event_name == 'pull_requests' && github.event.label.name == 'sp.02'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          custom_field_values: ${{ env.project_sp_02 }}
      - name: Set StoryPoints to 3
        if: github.event_name == 'pull_requests' && github.event.label.name == 'sp.03'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          custom_field_values: ${{ env.project_sp_03 }}
      - name: Set StoryPoints to 5
        if: github.event_name == 'pull_requests' && github.event.label.name == 'sp.05'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          custom_field_values: ${{ env.project_sp_05 }}
      - name: Set StoryPoints to 8
        if: github.event_name == 'pull_requests' && github.event.label.name == 'sp.08'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          custom_field_values: ${{ env.project_sp_08 }}
      - name: Set StoryPoints to 13
        if: github.event_name == 'pull_requests' && github.event.label.name == 'sp.13'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          custom_field_values: ${{ env.project_sp_13 }}
